In [13]:
import pandas as pd
import numpy as np

# dataframe的创建方式
# 通过series创建
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df = pd.DataFrame({
    '第一列': s1,
    '第二列': s2
})
# print(type(df))
# print(type(df['第一列']))
# 通过字典创建
df = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'name': ['唐僧', '孙悟空', '猪八戒', '沙和尚', '白龙马'],
    'age': [30, 999, 888, 777, 666],
    'score': [66.6, 77.7, 88.8, 99.9, 100]
}, index=[1, 2, 3, 4, 5], columns=['name', 'score', 'age'])
df

  name  score  age
1   唐僧   66.6   30
2  孙悟空   77.7  999
3  猪八戒   88.8  888
4  沙和尚   99.9  777
5  白龙马  100.0  666

In [16]:
# dataframe的属性
print(f'行索引：{df.index}')
print(f'列标签：{df.columns}')
print(f'值：{df.values}')

行索引：Index([1, 2, 3, 4, 5], dtype='int64')
列标签：Index(['name', 'score', 'age'], dtype='str')
值：[['唐僧' 66.6 30]
 ['孙悟空' 77.7 999]
 ['猪八戒' 88.8 888]
 ['沙和尚' 99.9 777]
 ['白龙马' 100.0 666]]

In [21]:
print(f'维度：{df.ndim}')
print(f'数据类型：\n{df.dtypes}')
print(f'形状：{df.shape}')
print(f'元素个数：{df.size}')

维度：2
数据类型：
name         str
score    float64
age        int64
dtype: object
形状：(5, 3)
元素个数：15

In [29]:
# 转置
# print(df.T)
df

  name  score  age
1   唐僧   66.6   30
2  孙悟空   77.7  999
3  猪八戒   88.8  888
4  沙和尚   99.9  777
5  白龙马  100.0  666

In [51]:
# 获取元素
# 某行
print(df.loc[1])
print(df.iloc[0])

name       唐僧
score    66.6
age        30
Name: 1, dtype: object
name       唐僧
score    66.6
age        30
Name: 1, dtype: object

In [55]:
# 某列
print(df.loc[:, 'name'])
print(df.iloc[:, 0])

1     唐僧
2    孙悟空
3    猪八戒
4    沙和尚
5    白龙马
Name: name, dtype: str
1     唐僧
2    孙悟空
3    猪八戒
4    沙和尚
5    白龙马
Name: name, dtype: str

In [61]:
# 单个数据
print(df.at[3, 'score'])
print(df.iat[2, 1])
print(df.loc[3, 'score'])
print(df.iloc[2, 1])

88.8
88.8
88.8
88.8

In [65]:
# 获取单列数据
print(df['name'])
print(df.name)

1     唐僧
2    孙悟空
3    猪八戒
4    沙和尚
5    白龙马
Name: name, dtype: str
1     唐僧
2    孙悟空
3    猪八戒
4    沙和尚
5    白龙马
Name: name, dtype: str

In [67]:
# 获取多列数据
df[['name', 'score']]

  name  score
1   唐僧   66.6
2  孙悟空   77.7
3  猪八戒   88.8
4  沙和尚   99.9
5  白龙马  100.0

In [69]:
# 查看部分数据
df.head(2)

  name  score  age
1   唐僧   66.6   30
2  孙悟空   77.7  999

In [70]:
df.tail(3)

  name  score  age
3  猪八戒   88.8  888
4  沙和尚   99.9  777
5  白龙马  100.0  666

In [74]:
# 使用布尔索引筛选数据
print(df[df.score > 80])
df[(df.score > 80) & (df.age < 800)]

  name  score  age
3  猪八戒   88.8  888
4  沙和尚   99.9  777
5  白龙马  100.0  666

  name  score  age
4  沙和尚   99.9  777
5  白龙马  100.0  666

In [82]:
# 随机抽样
df.sample(3)

  name  score  age
3  猪八戒   88.8  888
2  孙悟空   77.7  999
5  白龙马  100.0  666

In [83]:
# 常用方法
# https://www.yuque.com/jyafoo/backend/dp6fygyw1s2gur3g#va4Ji